### ISSUE TITLE
ENT is shown as C-m

### ISSUE THREAD

**Issue by takaxp** [chuntaro/emacs-keypression#2]
When I type "ENT", then "C-m" is displayed in keycaster.

I tried the following code in `keycaster-pre-command`,
```
(message "%s - %s - %s"
  (keycaster--keys-to-string (this-command-keys-vector))
  (key-description (this-command-keys))
  (this-command-keys))
```

and I received the following:

```
C-m - RET - ^M
```

I think `key-description` will help this issue.

**Comment by takaxp** [comment]
Additionally, in case the following:
```
(message "%s - %s - %s"
  (keycaster--keys-to-string (this-command-keys-vector))
  (key-description (this-command-keys-vector))
  (this-command-keys-vector))
```
then,
```
C-m - RET - [13]
```

We can see similar issue on typing "delete", it shows:
```
^? - DEL - [127]
```

Best,
Takaaki

**Comment by chuntaro** [comment]
Modified to use `key-description' and committed code.
I was able to reduce unnecessary code! Thanks!

**Comment by takaxp** [comment]
Good for me!
