### ISSUE TITLE
not compatible with ace-window

### ISSUE THREAD

**Issue by stardiviner** [chuntaro/emacs-keypression#5]
I tried this package, found that it is not compatible with `ace-window`. `keypression` will take the first window number. Maybe `keypression` frame and window should be ignored by `ace-window`.

**Comment by chuntaro** [comment]
Try the following settings.
The ace-window will now ignore the keypression window.
```emacs-lisp
(require 'ace-window)
(add-to-list 'aw-ignored-buffers 'fundamental-mode)

;; or

(require 'keypression)
(add-hook 'keypression-mode-hook
          (lambda ()
            (when keypression-mode
              (mapc (lambda (buf)
                      (add-to-list 'aw-ignored-buffers (buffer-name buf)))
                    keypression--buffers))))
```

**Comment by stardiviner** [comment]
This dirty hack workaround fix my problem. Thanks
