### ISSUE TITLE
self-insert hides previous line

### ISSUE THREAD

**Issue by perstar** [chuntaro/emacs-keypression#6]
When quickly typing     C-f a      first "C-f" is shown, but then immediately replaced with "a".
I expceted "C-f" to still be shown until it's time for that to fade away.

There is common code for self-insert and repeated keys with comment ";; Just rewrite the bottom line.".
This is good for repeated keys, but not for self-insert.

**Comment by chuntaro** [comment]
Thanks for the report!
It's fixed.
