### ISSUE TITLE
Feature request: handling prefix arguments

### ISSUE THREAD

**Issue by perstar** [chuntaro/emacs-keypression#7]
It would be great if prefix arguments done with digit-argument, negative-argument and universal-argument were put in the same frame as their following command. So when pressing

`   C-1 C-7 C-f`

first "C-1" would be shown, then extended to "C-1 C-7" and then extended to "C-1 C-7 C-f", instead of being in three different frames.

**Comment by chuntaro** [comment]
It's implemented!
